### ISSUE TITLE
Add support for BuildArch

### ISSUE THREAD

**Issue by nap** [monai/brass#1]
Hi, I would like to request the ability to specify which arch the RPM is to be generated for.
In the spec file, you can add a `BuildArch` parameter to get `name-version-release.architecture.rpm`.

Generating package with no arch is useful for configuration files and others.
Therefore you need to be able to specify something like:
`BuildArch: noarch`

Thanks

```
BuildArch: If you're packaging files that are architecture-independent (e.g. shell scripts, data files), then add "BuildArch: noarch". The architecture for the binary RPM will then be "no arch".
```

From https://fedoraproject.org/wiki/How_to_create_an_RPM_package#SPEC_file_overview

**Comment by monai** [comment]
This project is deprecated and superseded by [gulp-brass](https://github.com/monai/gulp-brass). gulp-brass supports [target](https://docs.fedoraproject.org/ro/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch19s04s02.html) option, for example:

``` js
var options = {
  ...
  target: 'noarch-centos-linux',
  ...
};
var rpm = brass.create(options);
```
